# Generated by Django 2.0.5 on 2018-05-25 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Nnewss',
            new_name='News',
        ),
    ]
